# Generated by Django 2.0.5 on 2018-05-20 07:46

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField()),
                ('author', models.ForeignKey(on_delete='null', to=settings.AUTH_USER_MODEL)),
                ('base_task_id', models.ForeignKey(on_delete='null', to='task_tracker_app.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(on_delete='null', to='task_tracker_app.Type'),
        ),
    ]
