# Generated by Django 2.0.5 on 2018-05-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='base_task_id',
            field=models.ForeignKey(default='null', on_delete='null', to='task_tracker_app.Task'),
        ),
    ]
