# Generated by Django 2.0.5 on 2018-05-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker_app', '0002_auto_20180520_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='base_task_id',
            field=models.ForeignKey(null=True, on_delete='null', to='task_tracker_app.Task'),
        ),
    ]
