# Generated by Django 2.0.5 on 2018-05-20 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker_app', '0005_auto_20180520_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='base_task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='task_tracker_app.Task'),
        ),
    ]
